# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/randseq',
                'doc_host': 'https://dbikard.github.io',
                'git_url': 'https://github.com/dbikard/randseq',
                'lib_path': 'randseq'},
  'syms': {'randseq.core': {'randseq.core.foo': ('core.html#foo', 'randseq/core.py')}}}
