"""visualizing the results"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/02_plotting.ipynb.

# %% auto 0
__all__ = ['plot_motif_analysis']

# %% ../nbs/02_plotting.ipynb 3
import pandas as pd
import matplotlib.pyplot as plt
import os
from .core import find_restricted_motifs
from .utils import calculate_log2fc, get_motif_presence_in_library

# %% ../nbs/02_plotting.ipynb 5
def plot_motif_analysis(counts_df, sample_col, ref_col, flexible_motifs_df, 
                                   left_context_str, right_context_str, 
                                   title_main="Flexible Motif Analysis", pseudocount=1):
    """
    Generates two subplots for position-independent motifs, considering sequence context.
    """
    motif_presence_df = get_motif_presence_in_library(
            counts_df.index.tolist(), left_context_str, right_context_str, flexible_motifs_df
        )

    # --- Minimal defaulting for flexible_motifs_df to prevent immediate errors ---
    # If it's not a valid DataFrame with 'motif' and 'pattern', treat as no motifs.
    if not (isinstance(flexible_motifs_df, pd.DataFrame) and \
            'motif' in flexible_motifs_df.columns and \
            'pattern' in flexible_motifs_df.columns): # pattern needed for dummy
        flexible_motifs_df = pd.DataFrame(columns=['motif', 'pattern'])
    # Note: Other inputs (counts_df, sample_col, etc.) are now assumed to be valid by the caller.

    # --- Data Preparation ---
    plot_df = counts_df.copy()
    plot_df['sample_numeric'] = pd.to_numeric(plot_df[sample_col], errors='coerce')
    plot_df['ref_numeric'] = pd.to_numeric(plot_df[ref_col], errors='coerce')

    total_sample = plot_df['sample_numeric'].sum()
    total_ref = plot_df['ref_numeric'].sum()

    if total_sample == 0 or total_ref == 0:
        plot_df['y_plot_values'] = plot_df['sample_numeric'].fillna(0) + pseudocount
        plot_df['x_plot_values'] = plot_df['ref_numeric'].fillna(0) + pseudocount
        norm_label_suffix = f"(Counts + {pseudocount}, log scale) - Norm. Failed"
    else:
        plot_df['y_plot_values'] = (plot_df['sample_numeric'] / total_sample * 1e6).fillna(0) + pseudocount
        plot_df['x_plot_values'] = (plot_df['ref_numeric'] / total_ref * 1e6).fillna(0) + pseudocount
        norm_label_suffix = f"(CPM + {pseudocount}, log scale)"

    # --- Plotting Setup ---
    fig, axes = plt.subplots(1, 1, figsize=(10, 8))
    fig.suptitle(title_main, fontsize=16)
    ax_scatter_flex = axes
    ax_scatter_flex.scatter(plot_df['x_plot_values'], plot_df['y_plot_values'], color='grey', alpha=0.5, s=10, label='All Sequences')
    for _ , motif in flexible_motifs_df.iterrows():
        df_flt=plot_df.loc[motif_presence_df[motif['motif']].values]
        ax_scatter_flex.scatter(df_flt['x_plot_values'], df_flt['y_plot_values'], alpha=0.5, s=10, label=motif['motif'])
    ax_scatter_flex.loglog()
    ax_scatter_flex.legend()
    plt.show()

