"""useful basic functions

Docs: https://dbikard.github.io/randseq/utils.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/01_utils.ipynb.

# %% auto #0
__all__ = ['IUPAC_DNA_TO_BASES', 'IUPAC_DNA_TO_REGEX', 'IUPAC_COMPLEMENT', 'IUPAC_EXPAND', 'IUPAC_COLLAPSE', 'calculate_log2fc',
           'revcomp', 'get_rebase_motifs', 'canonical_motif', 'get_lib_seq_context', 'check_specific_matches_broad',
           'find_broad_in_specific', 'get_motif_filter_with_context', 'generate_tuple_combinations',
           'filter_symmetric_tuples', 'get_patterns', 'get_custom_motif_presence_in_library',
           'get_log2fc_distribution_by_motif', 'motif_distance', 'merge_motifs', 'find_iupac_equivalent_motifs']

# %% ../nbs/01_utils.ipynb #d56a7712
import pandas as pd
import re
import numpy as np
import os
import itertools
from random import choice
from itertools import combinations
from collections import deque

# %% ../nbs/01_utils.ipynb #96f9919a
# IUPAC DNA codes mapping for sequence generation
IUPAC_DNA_TO_BASES = {
    'A': ['A'], 'C': ['C'], 'G': ['G'], 'T': ['T'], 'R': ['A', 'G'],
    'Y': ['C', 'T'], 'S': ['G', 'C'], 'W': ['A', 'T'], 'K': ['G', 'T'],
    'M': ['A', 'C'], 'B': ['C', 'G', 'T'], 'D': ['A', 'G', 'T'],
    'H': ['A', 'C', 'T'], 'V': ['A', 'C', 'G'], 'N': ['A', 'C', 'G', 'T']
}

# IUPAC DNA codes mapping for regex conversion
IUPAC_DNA_TO_REGEX = {
    'A': 'A', 'C': 'C', 'G': 'G', 'T': 'T', 'R': '[AG]', 'Y': '[CT]',
    'S': '[GC]', 'W': '[AT]', 'K': '[GT]', 'M': '[AC]', 'B': '[CGT]',
    'D': '[AGT]', 'H': '[ACT]', 'V': '[ACG]', 'N': '[ATGC]'
}

# IUPAC DNA codes for reverse complement
IUPAC_COMPLEMENT = {
    'A': 'T', 'T': 'A', 'C': 'G', 'G': 'C',
    'R': 'Y', 'Y': 'R', 'S': 'S', 'W': 'W',
    'K': 'M', 'M': 'K', 'B': 'V', 'V': 'B',
    'D': 'H', 'H': 'D', 'N': 'N'
}


# %% ../nbs/01_utils.ipynb #74913579
def calculate_log2fc(df, reference_column='MFDpir', count_threshold=20, pseudocount=1):
    """
    Filters a DataFrame, normalizes columns by sum, calculates log2 fold change
    relative to a reference column, and drops the reference column.

    Args:
        df (pd.DataFrame): Input DataFrame (rows=features, columns=samples).
        reference_column (str): Name of the reference sample column.
        count_threshold (int): Minimum count in reference column to keep a feature.
        pseudocount (float): Value added to normalized counts before log2FC.

    Returns:
        pd.DataFrame: DataFrame with log2 fold change values. None if reference
                      column is missing. Empty DataFrame if all rows are filtered out.
    """
    
    df = df.replace(np.nan,0)
    if reference_column not in df.columns:
        print(f"Error: Reference column '{reference_column}' not found in DataFrame.")
        return None

    # 1. Filter rows
    df_filtered = df[df[reference_column] > count_threshold].copy()
    if df_filtered.empty:
        print("DataFrame is empty after filtering.")
        return pd.DataFrame()

    # 2. Add pseudocount
    # The pseudocount is added here, before normalization.
    df_with_pseudocount = df_filtered + pseudocount

    # 3. Normalize each column by its sum
    # Normalization is now performed on the data that includes the pseudocount.
    # df.sum(axis=0) calculates sum for each column.
    # .div performs element-wise division, axis=1 aligns column_sums with columns.
    column_sums = df_with_pseudocount.sum(axis=0)
    
    # Handle cases where column_sums might be zero (e.g., if all values were -pseudocount after filtering, though unlikely with positive counts)
    # If a column sum is 0 after adding pseudocount, it implies an issue or very specific data.
    # Division by zero will result in NaN or inf.
    df_processed = df_with_pseudocount.div(column_sums, axis=1)

    # Check if reference column still exists (it should)
    if reference_column not in df_processed.columns:
        # This check is crucial as operations might alter columns if not handled carefully.
        print(f"Error: Reference column '{reference_column}' lost during processing.")
        return None
        
    reference_values = df_processed[reference_column]

    # 4. Calculate log2FC
    # .div performs element-wise division, axis=0 aligns reference_values (a Series) with rows of df_processed.
    log2fc_df = np.log2(df_processed.div(reference_values, axis=0))
    
    # Columns are already named correctly from df_processed.

    # 5. Drop the reference column's own log2FC (which will be ~zeros)
    if reference_column in log2fc_df.columns:
        log2fc_df = log2fc_df.drop(columns=[reference_column])
    else:
        print(f"Warning: Reference column '{reference_column}' not found in log2fc_df for dropping.")
        
    return log2fc_df

# %% ../nbs/01_utils.ipynb #44e4aa1e
def revcomp(seq:str):
    '''Computes the reverse complement of a sequence'''
    trns=str.maketrans("ATGCN","TACGN")
    return seq.upper().translate(trns)[::-1]

# %% ../nbs/01_utils.ipynb #04af769a
_REBASE_MOTIFS = None

def get_rebase_motifs():
    """The REBASE Gold Standard recognition motifs shipped with the package.

    Returns a `set` of IUPAC motif strings (n=983, downloaded 2025-12-03). Used by
    `canonical_motif` to decide which strand to report a motif on. Read once and cached.
    """
    global _REBASE_MOTIFS
    if _REBASE_MOTIFS is None:
        from randseq.data import get_data_dir
        path = os.path.join(get_data_dir(), 'rebase_gold_standard_motifs.txt')
        with open(path) as fh:
            _REBASE_MOTIFS = {line.strip().upper() for line in fh if line.strip()}
    return _REBASE_MOTIFS

# %% ../nbs/01_utils.ipynb #21042f37
def canonical_motif(motif, rebase_motifs=None):
    """Return the strand `motif` should be reported on.

    A motif and its reverse complement describe the same recognition site and always carry the
    same statistics, so exactly one of them should appear in the results. Prefer the strand that
    REBASE uses; if REBASE knows neither (or both), fall back to the alphabetically first strand,
    which is arbitrary but identical on every run.

    Args:
        motif (str): An IUPAC motif, e.g. `'GAGACC'` or `'CACNNNNGTAT'`.
        rebase_motifs (set, optional): Motif set to match against. Defaults to
            `get_rebase_motifs()`. Pass an explicit set to test or to use a different reference.

    Returns:
        str: `motif` or its reverse complement.
    """
    if rebase_motifs is None:
        rebase_motifs = get_rebase_motifs()
    motif = motif.upper()
    rc = revcomp(motif)
    in_fwd, in_rev = motif in rebase_motifs, rc in rebase_motifs
    if in_fwd and not in_rev:
        return motif
    if in_rev and not in_fwd:
        return rc
    return min(motif, rc)

# %% ../nbs/01_utils.ipynb #3eca7610
def get_lib_seq_context(seqs,left,right):
    """
    Generates a list of sequences by combining a left and right sequence with each sequence in the input list.
    
    Args:
        seqs (list): List of sequences to be combined.
        left (str): Left sequence to prepend.
        right (str): Right sequence to append.

    Returns:
        list: List of combined sequences.
    """
    left=left.upper()
    right=right.upper()
    lib=[left+r+right for r in seqs]
    return lib

# %% ../nbs/01_utils.ipynb #850fe0d6
def _generate_sequences_from_iupac(iupac_pattern_str):
    """Generates concrete DNA sequences from an IUPAC pattern."""
    if not iupac_pattern_str:
        return ['']
    possible_bases = [IUPAC_DNA_TO_BASES[c] for c in iupac_pattern_str.upper()]
    return ["".join(combo) for combo in itertools.product(*possible_bases)]

def _convert_iupac_to_regex(iupac_pattern_str):
    """Converts an IUPAC pattern to a regex string."""
    if not iupac_pattern_str:
        return ''
    return "".join([IUPAC_DNA_TO_REGEX[c] for c in iupac_pattern_str.upper()])

def _get_reverse_complement_iupac(iupac_pattern_str):
    """Computes the reverse complement of a DNA sequence in IUPAC format."""
    reversed_pattern = iupac_pattern_str.upper()[::-1]
    return "".join([IUPAC_COMPLEMENT[c] for c in reversed_pattern])


# %% ../nbs/01_utils.ipynb #16da8b97
def check_specific_matches_broad(specific, broad):
  """
  Checks if a 'specific' string matches a 'broad' string with a wildcard rule.

  This function compares two strings of the same length. The character 'N' in 
  the 'broad' string acts as a wildcard that can match any single character 
  in the 'specific' string at the same position. An 'N' in the 'specific' 
  string does not have any special meaning and is treated as a literal 'N'.

  Args:
    specific: The string that is being checked.
    broad: The string that contains the pattern, where 'N' is a wildcard.

  Returns:
    True if the 'specific' string matches the 'broad' pattern, False otherwise.
  """
  if len(specific) != len(broad):
    return False

  for spec_char, broad_char in zip(specific, broad):
    if spec_char == broad_char or broad_char == 'N':
      continue
    return False
  return True

def find_broad_in_specific(specific, broad):
  """
  Finds if a 'broad' DNA motif exists within a 'specific' DNA sequence, checking
  both forward and reverse complement orientations of the motif.

  If len(specific) < len(broad), it's impossible to find the motif, so it
  returns False. It first checks for the motif in the forward direction. If no match
  is found, it checks for the reverse complement of the motif.

  Args:
    specific: The DNA sequence to be searched within.
    broad: The DNA motif (pattern with 'N' wildcards) to search for.

  Returns:
    True if 'broad' or its reverse complement is found in 'specific', False otherwise.
  """
  if len(specific) < len(broad):
    return False
  
  broad_len = len(broad)
  if broad_len == 0:
      return True

  # 1. Check the forward orientation
  is_forward_match = any(check_specific_matches_broad(specific[i:i + broad_len], broad) 
                         for i in range(len(specific) - broad_len + 1))
  
  if is_forward_match:
    return True

  # 2. If no forward match, check the reverse complement orientation
  broad_rev_comp = revcomp(broad)
  is_reverse_match = any(check_specific_matches_broad(specific[i:i + broad_len], broad_rev_comp) 
                         for i in range(len(specific) - broad_len + 1))

  return is_reverse_match

# %% ../nbs/01_utils.ipynb #dfbdb2fc
def get_motif_filter_with_context(df, left_context, right_context, motif):
    """Boolean filter selecting sequences that contain `motif`, on either strand.

    The motif is matched against the sequence *with its flanking vector context restored*,
    because a recognition site can straddle the junction between the random insert and the
    backbone — several of the motifs recovered from real data do exactly that.

    Both orientations are searched, since a site and its reverse complement are the same site.
    That is also why a motif and its reverse complement always carry identical statistics, and
    therefore why only one of them should ever be reported (see `canonical_motif`).

    Args:
        df: DataFrame or Series whose **index** holds the DNA sequences.
        left_context, right_context: the vector sequence flanking the insert.
        motif: an IUPAC motif, e.g. `'GGTCTC'` or `'CACNNNNGTAC'`.

    Returns:
        pd.Series: boolean, indexed like `df`.
    """
    try:
        fwd = re.compile(_convert_iupac_to_regex(motif), re.IGNORECASE)
        rev = re.compile(_convert_iupac_to_regex(_get_reverse_complement_iupac(motif)),
                         re.IGNORECASE)
    except (KeyError, ValueError, re.error):
        # An unparseable motif matches nothing rather than raising, so one bad candidate
        # cannot abort a whole strain panel.
        return pd.Series(False, index=df.index)

    def present(seq):
        full = f"{left_context}{seq}{right_context}"
        return bool(fwd.search(full) or rev.search(full))

    return df.index.to_series().apply(present)

# %% ../nbs/01_utils.ipynb #3e05601c
def _get_filter_for_motif(series, motif, left_context, right_context):
    """`get_motif_filter_with_context` with the argument order used inside the pipeline.

    Kept as a separate name because `get_motif_filter_with_context` is public API that
    external scripts call; this one exists only so internal call sites read naturally.
    """
    return get_motif_filter_with_context(series, left_context, right_context, motif)

# %% ../nbs/01_utils.ipynb #b8aa3df2
def generate_tuple_combinations(a1, a2, b1, b2, c1, c2):
  """
  Generates a list of tuples with all possible number combinations within given ranges.

  Args:
    a1: The starting number for the first position.
    a2: The ending number for the first position (inclusive).
    b1: The starting number for the second position.
    b2: The ending number for the second position (inclusive).
    c1: The starting number for the third position.
    c2: The ending number for the third position (inclusive).

  Returns:
    A list of tuples, where each tuple contains three numbers representing
    a unique combination from the specified ranges.
  """
  range_a = range(a1, a2 + 1)
  range_b = range(b1, b2 + 1)
  range_c = range(c1, c2 + 1)
  
  # Using itertools.product is more efficient for generating Cartesian products
  combinations = list(itertools.product(range_a, range_b, range_c))
  
  return combinations


# %% ../nbs/01_utils.ipynb #a800821a
def filter_symmetric_tuples(list_of_tuples):
    """
    Filters a list of 3-integer tuples, removing specific symmetric pairs.

    This function removes a tuple if another tuple exists in the list that is
    its mirror image by swapping the first and third elements. For example, 
    (1, 2, 3) is considered a symmetric pair with (3, 2, 1). When such a pair 
    is found, only the first one encountered in the original list is kept.

    Args:
        list_of_tuples: A list of tuples, where each tuple contains three integers.

    Returns:
        A new list of tuples with the symmetric pairs removed.
    """
    # This set will store the canonical representation of tuples we have 
    # already encountered. The canonical form is the smaller of a tuple and
    # its symmetric version, ensuring we can identify pairs efficiently.
    seen_canonical_forms = set()
    
    # This list will hold the final, filtered tuples.
    filtered_list = []

    # Iterate through each tuple in the input list.
    for tup in list_of_tuples:
        # Create the specific symmetric counterpart by swapping the first and last elements.
        symmetric_tup = (tup[2], tup[1], tup[0])

        # Determine the canonical form by picking the lexicographically smaller
        # of the original tuple and its symmetric version. This makes the
        # representation consistent for any pair.
        canonical_form = min(tup, symmetric_tup)

        # If the canonical form is already in our 'seen' set, it means we have
        # already processed this tuple or its symmetric pair, so we skip it.
        if canonical_form in seen_canonical_forms:
            continue

        # If the canonical form has not been seen, we add the original tuple
        # to our result list.
        filtered_list.append(tup)
        
        # Add the canonical form to the 'seen' set. This ensures that the
        # other member of the symmetric pair will be skipped if encountered later.
        seen_canonical_forms.add(canonical_form)
        
    return filtered_list

# %% ../nbs/01_utils.ipynb #4672972a
def get_patterns():
    patterns = generate_tuple_combinations(5,7,0,0,0,0) + generate_tuple_combinations(2,4,1,8,3,4)
    patterns = filter_symmetric_tuples(patterns)
    patterns = sorted(patterns, key=lambda x: (x[0]+x[2], x[1])) 
    return patterns

# %% ../nbs/01_utils.ipynb #11cec62c
def _custom_motif_to_regex(motif):
    """IUPAC letters -> regex character classes (e.g. R -> [AG], N -> [ATGC]);
    anything already inside [...] is kept as written, so '[AG]TAC' and 'RTAC' are equivalent."""
    out, in_class = [], False
    for ch in motif.upper():
        if ch == '[':
            in_class = True
        elif ch == ']':
            in_class = False
        out.append(ch if in_class or ch in '[]' else IUPAC_DNA_TO_REGEX.get(ch, ch))
    return ''.join(out)

# %% ../nbs/01_utils.ipynb #8bc924dc
def get_custom_motif_presence_in_library(short_sequences_list, left_context, right_context, motif_list):
    """
    Creates a DataFrame indicating the presence of flexible motifs in sequences (with context).

    Args:
        short_sequences_list (list): List of original short DNA sequences.
        left_context (str): Left context string to prepend.
        right_context (str): Right context string to append.
        motif_list (list): Motif strings using IUPAC codes (e.g. 'AACNNNNCTTT', 'RTACNNNNGTG')
                           and/or regex character classes (e.g. '[AG]TACNNNNGTG').

    Returns:
        pd.DataFrame: DataFrame with full sequences (with context) as index,
                      flexible motif strings as columns, and boolean values indicating presence.
    """
    full_sequences_with_context = get_lib_seq_context(short_sequences_list, left_context, right_context)

    # Filter out None entries from full_sequences_with_context which may arise from non-string inputs to get_lib_seq_context
    # and keep track of original indices to align with short_sequences_list if needed for other purposes,
    # though for this function, we just use the valid full sequences.
    valid_full_sequences = [seq for seq in full_sequences_with_context if isinstance(seq, str)]
    if not valid_full_sequences:
        print("No valid full sequences to process after adding context.")
        return pd.DataFrame()
    presence_data = []

    for full_seq_str in valid_full_sequences:
        row_data = {'full_sequence': full_seq_str}
        for flex_motif_str in motif_list:
            if not isinstance(flex_motif_str, str) or not flex_motif_str:
                row_data[flex_motif_str] = False # Or handle as error/skip
                continue
            regex_pattern = _custom_motif_to_regex(flex_motif_str)
            try:
                if re.search(regex_pattern, full_seq_str):
                    row_data[flex_motif_str] = True
                elif re.search(regex_pattern, revcomp(full_seq_str)):
                    row_data[flex_motif_str] = True
                else:
                    row_data[flex_motif_str] = False
            except re.error:
                # print(f"Warning: Regex error for motif '{flex_motif_str}' (pattern: '{regex_pattern}'). Marking as False.")
                row_data[flex_motif_str] = False
        presence_data.append(row_data)

    if not presence_data:
        return pd.DataFrame(index=valid_full_sequences, columns=motif_list)

    presence_df = pd.DataFrame(presence_data)
    if 'full_sequence' in presence_df.columns:
        presence_df = presence_df.set_index('full_sequence')
        
    return presence_df

# %% ../nbs/01_utils.ipynb #25b089de
def get_log2fc_distribution_by_motif(log2fc_df, left_context, right_context, motif_list, sample_columns=None):
    """
    Categorizes each sequence in log2fc_df by which motif (if any) it contains,
    and reshapes to long format for distribution comparison/plotting.

    Args:
        log2fc_df (pd.DataFrame): DataFrame of log2 fold change values, indexed by short
                                   sequence (rows=features, columns=samples).
        left_context (str): Left context string to prepend before motif search.
        right_context (str): Right context string to append before motif search.
        motif_list (list): List of motif strings (e.g. ['CAAGNNNNNGGT']), using 'N' as wildcard.
                            If a sequence matches multiple motifs, the LAST matching motif
                            in motif_list wins (same precedence as plot_motif_ggplot).
        sample_columns (list, optional): Subset of columns (samples) from log2fc_df to include.
                                          Defaults to all columns.

    Returns:
        pd.DataFrame: Long-format DataFrame with columns ['sequence', 'Motif_Category',
                      'sample', 'log2fc']. 'Motif_Category' is one of motif_list or 'Other'.
                      None if motif presence could not be computed.
    """
    if sample_columns is None:
        sample_columns = log2fc_df.columns.tolist()

    # Positionally aligned with log2fc_df.index (order preserved by get_lib_seq_context),
    # same approach as plot_motif_ggplot.
    presence_df = get_custom_motif_presence_in_library(
        log2fc_df.index.tolist(), left_context, right_context, motif_list
    )

    if presence_df.empty:
        print("Error: could not compute motif presence.")
        return None

    df = log2fc_df[sample_columns].copy()
    df['Motif_Category'] = 'Other'

    for motif in motif_list:
        df.loc[presence_df[motif].values, 'Motif_Category'] = motif

    index_name = df.index.name or 'index'
    long_df = (
        df.reset_index()
          .melt(id_vars=[index_name, 'Motif_Category'], value_vars=sample_columns,
                var_name='sample', value_name='log2fc')
          .rename(columns={index_name: 'sequence'})
    )

    return long_df

# %% ../nbs/01_utils.ipynb #17a297ed
IUPAC_EXPAND = {k: frozenset(v) for k, v in IUPAC_DNA_TO_BASES.items()}
IUPAC_COLLAPSE = {v: k for k, v in IUPAC_EXPAND.items()}
_N_SET = frozenset('ACGT')


def _raw_distance(m1: str, m2: str) -> int:
    """
    Positional mismatch count between two same-length motifs.
    Positions where either motif is N (fully ambiguous) are skipped.
    Returns -1 for different lengths.
    """
    if len(m1) != len(m2):
        return -1
    dist = 0
    for a, b in zip(m1, m2):
        sa = IUPAC_EXPAND.get(a, frozenset())
        sb = IUPAC_EXPAND.get(b, frozenset())
        if sa == _N_SET or sb == _N_SET:
            continue
        if sa != sb:
            dist += 1
    return dist


def motif_distance(m1: str, m2: str, consider_rc: bool = True) -> tuple[int, bool]:
    """
    Minimum mismatch distance between m1 and m2, optionally also comparing m1
    to the reverse complement of m2 (because RM sites are strand-independent).

    Returns (distance, used_rc): distance is -1 if lengths differ; used_rc is
    True if the reverse complement of m2 gave the shorter distance.
    """
    d_fwd = _raw_distance(m1, m2)
    if not consider_rc or d_fwd == -1:
        return d_fwd, False

    d_rc = _raw_distance(m1, _get_reverse_complement_iupac(m2))

    if d_rc < d_fwd:
        return d_rc, True
    return d_fwd, False


def merge_motifs(motifs: list[str]) -> str:
    """
    Merge a list of same-length motifs (already in a consistent orientation)
    into a single IUPAC string by taking the union of nucleotide sets per position.
    """
    out = []
    for i in range(len(motifs[0])):
        union = frozenset()
        for m in motifs:
            union = union | IUPAC_EXPAND.get(m[i], frozenset())
        out.append(IUPAC_COLLAPSE.get(union, 'N'))
    return ''.join(out)

# %% ../nbs/01_utils.ipynb #a22f3fdc
def _connected_components(n_nodes: int,
                          edges: list[tuple[int, int]]) -> list[list[int]]:
    """Union-find connected components over integer node indices 0..n_nodes-1."""
    parent = list(range(n_nodes))

    def find(x: int) -> int:
        while parent[x] != x:
            parent[x] = parent[parent[x]]
            x = parent[x]
        return x

    for u, v in edges:
        pu, pv = find(u), find(v)
        if pu != pv:
            parent[pu] = pv

    comps = {}
    for i in range(n_nodes):
        comps.setdefault(find(i), []).append(i)
    return list(comps.values())


def _assign_orientations(comp: list[int],
                         adj: dict[int, list[tuple[int, bool]]]) -> dict[int, bool]:
    """
    BFS from the first node of a component to assign a consistent orientation
    (forward / RC) to every other node, propagating along edges.

    adj[u] = [(v, used_rc), ...]  - used_rc=True means rc(m_v) was closer to m_u.
    Orientation logic for edge (u -> v, used_rc=r): orient[v] = orient[u] XOR r,
    i.e. if m_v must be flipped to align to m_u and m_u is already flipped,
    m_v ends up back in forward orientation.
    """
    orientation = {comp[0]: False}
    queue = deque([comp[0]])
    while queue:
        u = queue.popleft()
        for v, used_rc in adj.get(u, []):
            if v not in orientation:
                orientation[v] = orientation[u] ^ used_rc
                queue.append(v)
    # Safety net for nodes not reached from comp[0] (shouldn't happen)
    for node in comp:
        orientation.setdefault(node, False)
    return orientation

# %% ../nbs/01_utils.ipynb #2bee3446
def find_iupac_equivalent_motifs(
    df: pd.DataFrame,
    max_mismatches: int = 2,
    motif_col: str = 'motif',
    sample_col: str = None,
    consider_rc: bool = True,
) -> pd.DataFrame:
    """
    Find motifs that differ by at most *max_mismatches* nucleotides and collapse
    them with IUPAC ambiguity codes (within each sample if *sample_col* is given).

    Rules:
    - Only motifs of the same length are compared.
    - N positions are skipped when counting mismatches.
    - When consider_rc=True (default), dist(A, B) = min(dist(A,B), dist(A,rc(B))).
      If rc(B) was closer, B is flipped before merging so all motifs in a group
      share a consistent strand orientation.
    - Groups are found via connected components (transitivity: A~B and B~C
      -> all three merged even if A and C are > max_mismatches apart).

    Args:
        df: DataFrame with at least *motif_col*, e.g. the flexible motifs returned by
            find_restricted_motifs. Optional num_sequences / avg_log2fc /
            fraction_depleted columns are aggregated per group.
        max_mismatches: 1 or 2 recommended.
        motif_col: column containing motif sequences.
        sample_col: column with the sample / strain identifier; None treats the
            whole df as one sample.
        consider_rc: whether to also compare against the reverse complement.

    Returns:
        DataFrame with one row per merged group (including singletons, n_merged == 1):
        [sample_col,] merged_motif, original_motifs, original_motifs_oriented,
        n_merged, max_pairwise_mismatches, rc_used, and when available
        total_sequences, avg_log2fc_weighted, avg_fraction_depleted.
    """
    records = []
    groups = df.groupby(sample_col, sort=False) if sample_col else [(None, df)]

    for sample, grp in groups:
        grp = grp.reset_index(drop=True)
        motifs = grp[motif_col].str.upper().tolist()

        # Group row indices by motif length
        by_len = {}
        for i, m in enumerate(motifs):
            by_len.setdefault(len(m), []).append(i)

        for row_idxs in by_len.values():
            sub_motifs = [motifs[i] for i in row_idxs]
            n = len(sub_motifs)

            # Build edge list; track RC usage and build adjacency for BFS
            edges = []
            pairwise_dist = {}
            adj = {k: [] for k in range(n)}  # adj[u] = [(v, used_rc), ...], bidirectional

            for i, j in combinations(range(n), 2):
                d, used_rc = motif_distance(sub_motifs[i], sub_motifs[j], consider_rc=consider_rc)
                if d != -1 and 0 < d <= max_mismatches:
                    edges.append((i, j))
                    pairwise_dist[(i, j)] = d
                    adj[i].append((j, used_rc))
                    adj[j].append((i, used_rc))  # symmetric: rc(rc(m)) = m

            for comp in _connected_components(n, edges):
                # Put all motifs of the component on the same strand before merging
                orientations = _assign_orientations(comp, adj)
                oriented_motifs = [_get_reverse_complement_iupac(sub_motifs[k]) if orientations[k] else sub_motifs[k]
                                   for k in comp]
                raw_mots = [sub_motifs[k] for k in comp]

                max_d = 0
                for a, b in combinations(sorted(comp), 2):
                    max_d = max(max_d, pairwise_dist.get((a, b), 0))

                comp_rows = grp.iloc[[row_idxs[k] for k in comp]]

                rec = {sample_col: sample} if sample_col else {}
                rec.update({
                    'merged_motif':             merge_motifs(oriented_motifs),
                    'original_motifs':          ' | '.join(sorted(set(raw_mots))),
                    'original_motifs_oriented': ' | '.join(sorted(set(oriented_motifs))),
                    'n_merged':                 len(set(raw_mots)),
                    'max_pairwise_mismatches':  max_d,
                    'rc_used':                  any(orientations[k] for k in comp),
                })

                if 'num_sequences' in grp.columns:
                    weights = comp_rows['num_sequences'].to_numpy(dtype=float)
                    rec['total_sequences'] = int(weights.sum())
                else:
                    weights = np.ones(len(comp_rows))

                if 'avg_log2fc' in grp.columns:
                    rec['avg_log2fc_weighted'] = float(
                        np.average(comp_rows['avg_log2fc'].to_numpy(dtype=float), weights=weights))

                if 'fraction_depleted' in grp.columns:
                    rec['avg_fraction_depleted'] = float(comp_rows['fraction_depleted'].mean())

                records.append(rec)

    return pd.DataFrame(records)
