"""useful basic functions"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/01_utils.ipynb.

# %% auto 0
__all__ = ['bases', 'flatten', 'calculate_log2fc', 'revcomp', 'allseqs', 'get_all_sites', 'get_lib_seq_context',
           'get_motif_filter_with_context']

# %% ../nbs/01_utils.ipynb 3
import pandas as pd
import re
import numpy as np
import os
import ahocorasick 


# %% ../nbs/01_utils.ipynb 5
def calculate_log2fc(df, reference_column='MFDpir', count_threshold=20, pseudocount=1):
    """
    Filters a DataFrame, normalizes columns by sum, calculates log2 fold change
    relative to a reference column, and drops the reference column.

    Args:
        df (pd.DataFrame): Input DataFrame (rows=features, columns=samples).
        reference_column (str): Name of the reference sample column.
        count_threshold (int): Minimum count in reference column to keep a feature.
        pseudocount (float): Value added to normalized counts before log2FC.

    Returns:
        pd.DataFrame: DataFrame with log2 fold change values. None if reference
                      column is missing. Empty DataFrame if all rows are filtered out.
    """
    if reference_column not in df.columns:
        print(f"Error: Reference column '{reference_column}' not found in DataFrame.")
        return None

    # 1. Filter rows
    df_filtered = df[df[reference_column] > count_threshold].copy()
    if df_filtered.empty:
        print("DataFrame is empty after filtering.")
        return pd.DataFrame()

    # 2. Add pseudocount
    # The pseudocount is added here, before normalization.
    df_with_pseudocount = df_filtered + pseudocount

    # 3. Normalize each column by its sum
    # Normalization is now performed on the data that includes the pseudocount.
    # df.sum(axis=0) calculates sum for each column.
    # .div performs element-wise division, axis=1 aligns column_sums with columns.
    column_sums = df_with_pseudocount.sum(axis=0)
    
    # Handle cases where column_sums might be zero (e.g., if all values were -pseudocount after filtering, though unlikely with positive counts)
    # If a column sum is 0 after adding pseudocount, it implies an issue or very specific data.
    # Division by zero will result in NaN or inf.
    df_processed = df_with_pseudocount.div(column_sums, axis=1)

    # Check if reference column still exists (it should)
    if reference_column not in df_processed.columns:
        # This check is crucial as operations might alter columns if not handled carefully.
        print(f"Error: Reference column '{reference_column}' lost during processing.")
        return None
        
    reference_values = df_processed[reference_column]

    # 4. Calculate log2FC
    # .div performs element-wise division, axis=0 aligns reference_values (a Series) with rows of df_processed.
    log2fc_df = np.log2(df_processed.div(reference_values, axis=0))
    
    # Columns are already named correctly from df_processed.

    # 5. Drop the reference column's own log2FC (which will be ~zeros)
    if reference_column in log2fc_df.columns:
        log2fc_df = log2fc_df.drop(columns=[reference_column])
    else:
        print(f"Warning: Reference column '{reference_column}' not found in log2fc_df for dropping.")
        
    return log2fc_df

# %% ../nbs/01_utils.ipynb 8
def revcomp(seq:str):
    '''Computes the reverse complement of a sequence'''
    trns=str.maketrans("ATGCN","TACGN")
    return seq.upper().translate(trns)[::-1]

# %% ../nbs/01_utils.ipynb 10
bases=list("ATGC")
def allseqs(n,seqs=[""]):
    '''Recursive function that generates all possible sequences of length n
    seqs is a list of sequences to which we will add bases
    '''
    seqs=[s+b for s in seqs for b in bases]
    if len(seqs[0])<n:
        return allseqs(n,seqs)
    else:
        return seqs

# %% ../nbs/01_utils.ipynb 12
flatten = lambda l: [item for sublist in l for item in sublist]

# %% ../nbs/01_utils.ipynb 14
def get_all_sites(pattern):
    #generates a list of all sites that match the pattern
    return [s[:pattern[0]]+"N"*pattern[1]+s[pattern[0]:] for s in allseqs(pattern[0]+pattern[2])]


# %% ../nbs/01_utils.ipynb 16
def get_lib_seq_context(seqs,left,right):
    """
    Generates a list of sequences by combining a left and right sequence with each sequence in the input list.
    
    Args:
        seqs (list): List of sequences to be combined.
        left (str): Left sequence to prepend.
        right (str): Right sequence to append.

    Returns:
        list: List of combined sequences.
    """
    left=left.upper()
    right=right.upper()
    lib=[left+r+right for r in seqs]
    return lib

# %% ../nbs/01_utils.ipynb 18
def get_motif_filter_with_context(df, left_context, right_context, motif):
    """
    Returns a boolean filter for the DataFrame to select rows whose index (sequence)
    contains the motif (with ambiguity codes), when flanked by the provided left and right context,
    searching both the forward and reverse complement orientations.

    Args:
        df (pd.DataFrame): DataFrame with DNA sequences as index.
        left_context (str): DNA string to prepend to each sequence.
        right_context (str): DNA string to append to each sequence.
        motif (str): DNA motif (may include IUPAC ambiguous bases).

    Returns:
        pd.Series: Boolean filter for df, True where the motif is present (with context, any orientation).
    """

    # IUPAC ambiguity codes to regex
    iupac_dict = {
        'A': 'A', 'C': 'C', 'G': 'G', 'T': 'T',
        'R': '[AG]', 'Y': '[CT]', 'S': '[GC]', 'W': '[AT]',
        'K': '[GT]', 'M': '[AC]', 'B': '[CGT]', 'D': '[AGT]',
        'H': '[ACT]', 'V': '[ACG]', 'N': '[ACGT]'
    }
    # Build regex pattern from motif
    motif_regex = ''.join(iupac_dict.get(base.upper(), base) for base in motif)
    compiled = re.compile(motif_regex, re.IGNORECASE)

    def contains_motif(seq):
        seq_with_context = f"{left_context}{seq}{right_context}"
        seq_with_context_rc = revcomp(seq_with_context)
        return bool(compiled.search(seq_with_context) or compiled.search(seq_with_context_rc))

    return df.index.to_series().apply(contains_motif)
